//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Example.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonCar
    {
        public int PersonID { get; set; }
        public string CarName { get; set; }
        public string CarPlak { get; set; }
    
        public virtual tbl_People tbl_People { get; set; }
    }
}
